#!/bin/sh
#
# Initialize the system for prepare-disk
#

which apk >/dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Alpine Linux required" >&2
  exit 1
fi

set -e -x

# Setup APK repositories if necessary
grep -q http /etc/apk/repositories || setup-apkrepos

sudo apk add zfs
