#!/bin/sh
#
# Initialize the system for prepare-disk
#

which apk >/dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Alpine Linux required" >&2
  exit 1
fi

set -e -x

# Setup APK repositories if necessary
grep -q http /etc/apk/repositories || setup-apkrepos

# Uncomment the first commented line in /etc/apk/repositories, which should be the community repository
sed -E '1,/#/s/#//' /etc/apk/repositories -i""

# Install required packages 
apk add haveged gptfdisk sgdisk
