#!/bin/sh
#
# Initialize the system for prepare-disk
#

which apk >/dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Detected environment: Alpine Linux (apk)"
  set -e -x

  # Setup APK repositories if necessary
  grep -q http /etc/apk/repositories || setup-apkrepos

  # Uncomment the first commented line in /etc/apk/repositories, which should be the community repository
  sed -E '1,/#/s/#//' /etc/apk/repositories -i""

  # Install required packages 
  apk add haveged gptfdisk sgdisk e2fsprogs syslinux
  
  exit 0
fi

which pacman >/dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Detected environment: Arch Linux (pacman)"
  set -e -x

  pacman -Sy haveged gdisk e2fsprogs syslinux
  
  exit 0
fi

which apt >/dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Detected environment: Debian (apt)"
  set -e -x

  apt update
  apt install haveged gdisk e2fsprogs syslinux extlinux

  exit 0
fi

echo "Error: Unsupported environment" >&2
exit 1
